services:
  traefik:
    image: "traefik:v2.5.3"
    restart: always
    command:
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --entrypoints.websecure.address=:443
      - --providers.docker
      - --log.level=DEBUG
      - --log.filePath=/logs/traefik.log
      - --api
      # - --certificatesresolvers.leresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
      - --certificatesresolvers.leresolver.acme.email=oeway007@gmail.com
      - --certificatesresolvers.leresolver.acme.storage=acme/acme.json
      - --certificatesresolvers.leresolver.acme.tlschallenge=true
      - --certificatesresolvers.leresolver.acme.httpchallenge=true
      - --certificatesresolvers.leresolver.acme.httpchallenge.entrypoint=web
      - --accesslog.filepath=/logs/access.log
      - --accesslog.filters.statuscodes=200,300-302
      - --accesslog.filters.retryattempts
      - --accesslog.filters.minduration=10ms
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    networks:
      - hypha-app-engine
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./acme:/acme"
      - "./logs:/logs"
networks:
  hypha-app-engine:
    external: true