name: Service Health Check

on:
  schedule:
    - cron: '*/9 * * * *'  # Every 9 minutes
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  check_services:
    runs-on: ubuntu-latest

    steps:
    - name: Initialize error log
      run: touch error.log

    - name: Check Incubator Control Service
      run: |
        response=$(curl -s -f https://hypha.aicell.io/reef-imaging/services/mirror-incubator-control/hello_world || echo "Service unreachable")
        if [ "$response" != "Hello world" ]; then
          echo "Incubator Control Service is down: $response" >> error.log
        fi
        
        task_status=$(curl -s -f https://hypha.aicell.io/reef-imaging/services/mirror-incubator-control/get_all_task_status || echo "{}")
        if echo "$task_status" | grep -q "failed"; then
          echo "Incubator Control Service has failed tasks" >> error.log
        fi

    - name: Check Microscope Control Service
      run: |
        response=$(curl -s -f https://hypha.aicell.io/squid-control/services/mirror-microscope-control-squid-1/hello_world || echo "Service unreachable")
        if [ "$response" != "Hello world" ]; then
          echo "Microscope Control Service is down: $response" >> error.log
        fi
        
        task_status=$(curl -s -f https://hypha.aicell.io/squid-control/services/mirror-microscope-control-squid-1/get_all_task_status || echo "{}")
        if echo "$task_status" | grep -q "failed"; then
          echo "Microscope Control Service has failed tasks" >> error.log
        fi

    - name: Check Robotic Arm Control Service
      run: |
        response=$(curl -s -f https://hypha.aicell.io/reef-imaging/services/mirror-robotic-arm-control/hello_world || echo "Service unreachable")
        if [ "$response" != "Hello world" ]; then
          echo "Robotic Arm Control Service is down: $response" >> error.log
        fi
        
        task_status=$(curl -s -f https://hypha.aicell.io/reef-imaging/services/mirror-robotic-arm-control/get_all_task_status || echo "{}")
        if echo "$task_status" | grep -q "failed"; then
          echo "Robotic Arm Control Service has failed tasks" >> error.log
        fi

    - name: Check if any services are down
      id: check_errors
      run: |
        if [ -s error.log ]; then
          echo "errors=true" >> $GITHUB_OUTPUT
          cat error.log
        else
          echo "All services are functioning normally"
        fi

    - name: Send Email if Errors
      if: steps.check_errors.outputs.errors == 'true'
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.example.com
        server_port: 587
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: "Service Health Check Alert"
        to: songtao.cheng@scilifelab.se
        from: songtao.cheng@scilifelab.se
        body: |
          The following services are down or have failed tasks:
          $(cat error.log)
